language: node_js
node_js: stable

install:
  - npm install
  - npm audit fix
  
script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "wyiyi"
  - git config user.email "1084896032@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force "https://$GH_TOKEN@$GH_REF" master:master

branches:
  only:
    - develop
env:
  global:
    - GH_REF: github.com/wyiyi/amber
