#菜单导航
menu:
  home: /
  archives: /archives
  about: /about
  #RSS: /atom.xml

#logo
logo: /abmer/images/logo.png

# favicon
favicon: /amber/images/favicon.ico

# site switch
site_search: true

# rss
rss: /atom.xml

# search post url
search_url: /search.xml

#畅言评论
changyan:
  appid: ''
  conf: ''
